export const KNOWN_EXAMS = {
  '1': 'DE LA INFORMACIÓN AL CONOCIMIENTO',
  '2': 'EL LENGUAJE EN LA RELACIÓN DEL HOMBRE CON EL MUNDO',
  '3': 'REPRESENTACIONES SIMBÓLICAS Y ALGORITMOS',
  '4': 'SER SOCIAL Y SOCIEDAD',
  '5': 'MI MUNDO EN OTRA LENGUA',
  '6': 'TECNOLOGÍA DE INFORMACIÓN Y COMUNICACIÓN',
  '7': 'TEXTOS Y VISIONES DEL MUNDO',
  '8': 'MATEMÁTICAS Y REPRESENTACIONES DEL SISTEMA NATURAL',
  '9': 'UNIVERSO NATURAL',
  '10': 'SOCIEDAD MEXICANA CONTEMPORÁNEA',
  '11': 'TRANSFORMACIONES EN EL MUNDO CONTEMPORÁNEO',
  '12': 'MI VIDA EN OTRA LENGUA',
  '13': 'ARGUMENTACIÓN',
  '14': 'VARIACIÓN EN PROCESOS SOCIALES',
  '15': 'CÁLCULO EN FENÓMENOS NATURALES Y PROCESOS SOCIALES',
  '16': 'HACIA UN DESARROLLO SUSTENTABLE',
  '17': 'EVOLUCIÓN Y SUS REPERCUSIONES SOCIALES',
  '18': 'ESTADÍSTICA EN FENÓMENOS NATURALES Y PROCESOS SOCIALES',
  '19': 'DINÁMICA EN LA NATURALEZA: EL MOVIMIENTO',
  '20': 'OPTIMIZACIÓN EN SISTEMAS NATURALES Y SOCIALES',
  '21': 'IMPACTO DE LA CIENCIA Y LA TECNOLOGÍA',
  '22': 'INFORMÁTICA',
}

export const DEFAULT_EXAMS = [{ number: '', name: '' }]

export const REQUIRED_FIELDS = ['name', 'matricula', 'etapa', 'oficina']
